FORMAT: 1A
HOST: https://oc-144-21-66-168.compute.oraclecloud.com:7002

# abc Media Catalogue API
The Music Catalogue API is provides access to abc's
digital media assets such as artits, albums and songs.

# Group Artists Resources
Artists related digital media resources.

## Search and Create Artists [/abccatalogue/artists{?limit,name,country,genre}]

+ Parameters
    + limit (number, optional)

        A limit on the number of artists to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`
        
    + name: Oasis (string, optional)

        The name of the artist.
        
    + country (string, optional)

        The country code an artists belongs to. Note that abc uses ISO 3166-1 alpha-2 for country codes 
        
        + Default: `GB`
        
    + genre (string, optional)

        A string to be used to search for a specific artist
    
### Search Artists [GET]
Returns all abc Artists that match the specified criteria.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + metadata (Search Metadata)
        
        + artists (array[Artist])

### Create Artist [POST]
Creates an Artist.

+ Request (text/Plain)
 
    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes (Artist)

+ Response 201 (application/json; charset=utf-8)

## Get and Update Artist [/abccatalogue/artists/{artist_id}]

+ Parameters

    + artist_id: art123456 (number, required)

        The unique ID for a specific artist
        
### Get Artist [GET]
Returns the details for a specific Artist such as bio and Albums.
        
+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Artist)

### Update Artist [PUT]
Updates an existing Artist.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes (Artist)

+ Response 200 (application/json; charset=utf-8)

## Get Artist Albums [/abccatalogue/artists/{artist_id}/albums]

+ Parameters

    + artist_id: art123456 (number, required)

        The unique ID for a specific artist
        
### Get Artist Albums [GET]
Returns all the Albums for the specified Artist. 

+ Request (text/plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + albums (array[Album])

# Group Albums Resources
Artists-related digital media resources.

## Search and Create Albums [/abccatalogue/albums{?limit,name,artist,genre}]

+ Parameters

    + limit (number, optional)

        A limit on the number of albums to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`
        
    + name (string, optional)

        A string to be used to search for a specific artist
        
    + artist (string, optional)

        The name of the artist 
        
    + genre (string, optional)

        A string to be used to search for a specific artist

### Search Albums [GET]
Returns Albums that match the specified criteria.

+ Request (text/plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + metadata (Search Metadata)
        
        + albums (array[Album])

### Create Album [POST]
Creates an Album. Artist ID most be provided.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes(Album)

+ Response 201 (application/json; charset=utf-8)

## Get and Update Album [/abccatalogue/albums/{album_id}]

+ Parameters

    + album_id: alb000456 (number, required)

        The unique ID for the album

### Get Album [GET]
Returns the details of a specific Album such as release date and Songs.

+ Request (text/plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes(Album)

### Update Album [POST]
Updates an existing Album.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes (Album)

+ Response 200 (application/json; charset=utf-8)

# Group Songs Media
Songs and Video digital media resources.

## Search and Create Songs  [/abccatalogue/songs{?limit,name,artist,genre}]

+ Parameters

    + limit (number, optional)

        A limit on the number of songs to be returned. Limit can range
        between 1 and 100 items.

        + Default: `10`
        
    + name (string, optional)

        A string to be used to search for a specific artist
        
    + artist (string, optional)

        The name of the artist 
        
    + genre (string, optional)

        A string to be used to search for a specific artist

### Search Songs [GET]
Returns all Songs that match the specified criteria.

+ Request (text/plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes
    
        + metadata (Search Metadata)
        
        + songs (array[Song])

### Create Song [POST]
Creates an Song. Album ID most be provided.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes (Song)

+ Response 201 (application/json; charset=utf-8)

## Get and Update Song  [/abccatalogue/songs/{song_id}]

+ Parameters

    + song_id: son003456 (number, required)

        The unique ID for a specific song

### Get Song  [GET]
Returns the details for a specific Song, such as length and streaming endpoints

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

+ Response 200 (application/json; charset=utf-8)

    + Attributes (Song)

### Update Song [POST]
Updates an existing Song.

+ Request (text/Plain)

    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Attributes (Song)

+ Response 200 (application/json; charset=utf-8)

## Add Song Media [/abccatalogue/songs/{song_id}/media]
Creates a media file e.g. MP3 or MP4 media file.

+ Parameters

    + song_id: son003456 (number, required)

        The unique ID for a specific song

### Add Song Media [POST]
Create a media file e.g. MP3 or MP4 media file.

 + Request (multipart/form-data;boundary=----BOUNDARY)
 
    + Headers

            api-key: 64b56ec7-cef0-4359-840d-3fb0eef9cfa7

    + Body

            ------BOUNDARY
            Content-Disposition: attachment; name="wonderwall"; filename="wondewall.mp3"
            Content-Type: audio/mpeg3

            data
            ------BOUNDARY--
            
+ Response 201 (application/json; charset=utf-8)

# Data Structures

## Search Metadata (object)
- total_count: 1 (number, required)
- result_count: 1 (number, required)
- offset: 1 (number, required)

## Artist (object)
- artist_name: Oasis (string, required)
- artist_id: art123456 (string, optional)
- country: UK (string, optional)
- bio: Oasis is a great band from Manchester (string, optional)
- genres: Rock, Pop (string, required)
- albums(array[Album], optional)
- _links (optional)
    - self
        - href: /v1/abccatalogue/artists/art12345 (string, required)
    - albums
        - href: /v1/abccatalogue/artists/art12345/albums (string, optional)

## Album (object)
- album_name: `(What's the Story) Morning Glory?` (string, required)
- album_id: alb000456 (string, optional)
- upc: 074646735121 (string, optional)

    Universal Product Code 

- release_date: 1995-10-02 (string, optional)
- song_count: 12 (number, required)
- length_seconds: 3006 (number, optional)
- artist(Artist, required)
- songs(array[Song], optional)
- _links (optional)
    - self
        - href: /v1/abccatalogue/albums/alb000456 (string, required)

## Song (object)
- song_name: Wonder wall (string, required)
- song_id: son003456 (string, optional)
- isrc: GBAAW9500189 (string, optional)

    International Standard Recording Code

- release_date: 1995-10-02 (string, optional)
- audio(optional)
    - format: mp3 (string, optional)
    - length_seconds: 259 (number, optional)
- video (optional)
    - format: mp4 (string, optional)
    - length_seconds: 279 (number, optional)
- artist(Artist, optional)
- album(Album, required
    - self
        - href: /v1/abccatalogue/songs/son003456 (string, required)
    - audio
        - format: mp3 (string, optional)
        - length_seconds: 259 (number, optional)
        - href: /v1/abccatalogue/songs/son003456/audio?format=mp3 (string, optional)
    - video
        - format: mp4 (string, optional)
        - length_seconds: 279 (number, optional)
        - href: /v1/abccatalogue/songs/son003456/audio?format=mp4 (string, optional)